spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5432/media_db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8087

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
